version: '3.9'

services:
  remote:
    image: lekliu/liuproxy-remote:v2.1
    container_name: liuproxy_remote_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # 将本地的configs目录完整挂载到容器中
      # 这样可以同时管理 local.ini 和未来的 servers.json
      - ./configs:/app/configs
    ports:
      # Web UI端口
      - "127.0.0.1:10089:10089"
    restart: unless-stopped